WssPmMVC2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WssPmMVC2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WssPmMVC2/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WssPmCommon2.Models;
using WssPmDataAccess;

namespace WssPmMVC2.Controllers
{
    public class PeopleController : Controller
    {
        //QualityAnalyst = 0x01,
        //BusinessAnalyst = 0x02,
        //DevelopmentLead = 0x04,
        //DevelopmentManager = 0x08,
        //ProductOwner = 0x10,
        //AssistanProductOwner = 0x20

        // GET: People
        public ActionResult Index()
        {
            var allPeople = WssPmSqlData.Instance.People.ToList();
            return View(allPeople);
        }

        public ActionResult IndexByRole(string roleName)
        {
            var role = (RoleType)Enum.Parse(typeof(RoleType), roleName);

            ViewBag.Role = roleName;
            ViewBag.RoleName = role.AsString();
            ViewBag.People = WssPmSqlData.Instance.People.ToList().Where(p => p.HasRole(role)).ToList();

            return View();
        }


        [HttpPost]
        public ActionResult Add(Person person)
        {
            WssPmSqlData.Instance.People.Add(person);
            WssPmSqlData.Instance.SaveChanges();

            return RedirectToAction("IndexByRole", new { roleName = person.RoleType().ToString() });
        }

        public ActionResult Add(string roleName)
        {
            var role = (RoleType)Enum.Parse(typeof(RoleType), roleName);
            ViewBag.Role = roleName;
            var person = new Person(role);

            return View(person);
        }

        public ActionResult Edit(int personId)
        {
            return View(personId);
        }

        [HttpPost]
        public ActionResult Edit(Person person)
        {
            var matchedPerson = WssPmSqlData.Instance.People.FirstOrDefault(p => p.Id == person.Id);
            if (matchedPerson != null)
            {
                matchedPerson.IsActive = person.IsActive;
                matchedPerson.LastName = person.LastName;
                matchedPerson.FirstName = person.FirstName;
                matchedPerson.Email = person.Email;
                matchedPerson.ContactType = person.ContactType;
            }
            WssPmSqlData.Instance.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WssPmMVC2/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WssPmCommon2.Models;
using WssPmDataAccess;

namespace WssPmMVC2.Controllers
{
    public class ProjectController : Controller
    {
        public ActionResult Index(List<Project> projectList = null)
        {
            //if (projectList == null || projectList.Count == 0) projectList = Project.SampleData();
            if (projectList == null || projectList.Count == 0) projectList = WssPmSqlData.Instance.Projects.ToList();
            //ViewData["ProjectList"] = Models.Project.SampleData();
            return View(projectList);
        }

        [HttpPost]
        public ActionResult Add(Project project)
        {
            WssPmSqlData.Instance.Projects.Add(project);
            WssPmSqlData.Instance.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(int projectId)
        {
            var matchingProduct = Project.SampleData().FirstOrDefault(p => p.Id == projectId);

            return View(matchingProduct);
        }
    }
}

WssPmMVC2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WssPmMVC2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WssPmMVC2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link href="~/Content/WssPmStyles.css" rel="stylesheet" type="text/css" />

<div class="jumbotron">
    <h1>WebstaurantStore - BA - Project Manager</h1>
</div>

<div class="row">

    <input type="button" value="Projects" onclick="location.href='@Url.Action("Index", "Project")'" />
    <input type="button" value="People" onclick="location.href='@Url.Action("Index", "People")'" />

</div>

WssPmMVC2/Views/People/Add.cshtml
@using WssPmCommon2.Models
@model Person
@{
    ViewBag.Title = "Add";
}

<h2>Add @ViewBag.RoleName</h2>

<table>
    <tr>
        <td>@Html.LabelFor(m => m.LastName)</td>
        <td>@Html.TextBoxFor(m => m.LastName)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.FirstName)</td>
        <td>@Html.TextBoxFor(m => m.FirstName)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.Email)</td>
        <td>@Html.TextBoxFor(m => m.Email)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.IsActive)</td>
        <td>@Html.CheckBoxFor(m => m.IsActive)</td>
    </tr>

</table>
@using (Html.BeginForm("Add", "People"))
{
    <input type="submit" value="Save" />
}

WssPmMVC2/Views/People/Index.cshtml
@using WssPmCommon2.Models

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/WssPmStyles.css" rel="stylesheet" type="text/css" />
<h2>All Contacts</h2>

<input type="button" value="Development Manager" onclick="location.href='@Url.Action("IndexByRole", "People", new { roleName = RoleType.DevelopmentManager.ToString() })'" />

<input type="button" value="Lead Developer" onclick="location.href='@Url.Action("IndexByRole", "People", new { roleName = RoleType.DevelopmentLead.ToString() })'" />

<input type="button" value="Business Analysts" onclick="location.href='@Url.Action("IndexByRole", "People", new { roleName = RoleType.BusinessAnalyst.ToString() })'" />

<input type="button" value="Quality Analysts" onclick="location.href='@Url.Action("IndexByRole", "People", new { roleName = RoleType.QualityAnalyst.ToString() })'" />

<input type="button" value="Product Owners" onclick="location.href='@Url.Action("IndexByRole", "People", new { roleName = RoleType.ProductOwner.ToString() })'" />

<input type="button" value="Assistant Product Owners" onclick="location.href='@Url.Action("IndexByRole", "People", new { roleName = RoleType.AssistanProductOwner.ToString() })'" />

<table>
    <tr>
        <td>Last Name</td>
        <td>First Name</td>
        <td>Email</td>
        <td>Roles</td>
        <td>Is Active</td>
    </tr>
    @foreach (var p in Model)
    {
        <tr>
            <td>@p.LastName</td>
            <td>@p.FirstName</td>
            <td>@p.Email</td>
            <td>@p.AllRoles()</td>
            <td>@p.IsActive</td>
        </tr>
    }
</table>

WssPmMVC2/Views/People/IndexByRole.cshtml
@using WssPmCommon2.Models

@{
    ViewBag.Title = Model;
}
<link href="~/Content/WssPmStyles.css" rel="stylesheet" type="text/css" />

<h2>@ViewBag.RoleName</h2>

@Html.ActionLink("Add", "Add", "People", new { roleName = ViewBag.Role }, null)

<br />
<table>
    <tr>
        <td>Last Name</td>
        <td>First Name</td>
        <td>Email</td>
        <td>IsActive</td>
    </tr>
    @foreach (var p in ViewBag.People)
    {
        <tr>
            <td>@p.LastName</td>
            <td>@p.FirstName</td>
            <td>@p.Email</td>
            <td>@p.IsActive</td>
        </tr>
    }
</table>

WssPmMVC2/Views/Project/Add.cshtml
@using WssPmCommon2.Models

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Project
@{

    using (Html.BeginForm("Add", "Project"))
    {
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
        <br />
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description)
        <br />
        @Html.LabelFor(m => m.StartDate)
        @Html.EditorFor(m => m.StartDate)
        <br />
        @Html.LabelFor(m => m.Deadline)
        @Html.EditorFor(m => m.Deadline)
        <br />
        @Html.LabelFor(m => m.EstimatedDone)
        @Html.EditorFor(m => m.EstimatedDone)
        <br />
        @Html.LabelFor(m => m.IsActive)
        @Html.CheckBoxFor(m => m.IsActive)
        <br />
        <input type="submit" value="Create" />
    }

}

WssPmMVC2/Views/Project/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model WssPmCommon2.Models.Project
@{
    <table>
        <tr>
            <td>@Html.LabelFor(m => m.Id)</td>
            <td>@Html.TextBoxFor(m => m.Id, new { @readonly = "readonly" })</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Name)</td>
            <td>@Html.TextBoxFor(m => m.Name)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Description)</td>
            <td>@Html.TextBoxFor(m => m.Description)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.StartDate)</td>
            <td>@Html.TextBoxFor(m => m.StartDate, "{0:MM/dd/yyyy}")</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.Deadline)</td>
            <td>@Html.TextBoxFor(m => m.Deadline, "{0:MM/dd/yyyy}")</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.EstimatedDone)</td>
            <td>@Html.TextBoxFor(m => m.EstimatedDone, "{0:MM/dd/yyyy}")</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.IsActive)</td>
            <td>@Html.CheckBoxFor(m => m.IsActive)</td>
        </tr>
    </table>
}

WssPmMVC2/Views/Project/Index.cshtml
@using WssPmCommon2

@model IEnumerable<WssPmCommon2.Models.Project>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>
<p>Hello from the Project Index View Template</p>
@Html.ActionLink("Add Project", "Add", "Project")
<br />
<table>
    <tr>
        <td width="150">Name</td>
        <td width="200">Description</td>
        <td width="80">Start Date</td>
        <td width="80">Deadline</td>
        <td width="80">ETA</td>
        <td width="80">Active</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Edit", "Project", new { projectId = item.Id }, null)
            </td>
            <td>@item.Description</td>
            <td>@item.StartDate.ToString("MM/dd/yyyy")</td>
            <td>@item.Deadline.ToString("MM/dd/yyyy")</td>
            <td>@item.EstimatedDone.ToString("MM/dd/yyyy")</td>
            <td>@Html.CheckBox("IsActive", @item.IsActive, new { disabled = "disabled" })</td>
        </tr>
    }
</table>

WssPmMVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>